---
title: "Resume"
author: "Abhishek Ajay (aa4266)"
date: "October 31, 2018"
output: 
  html_document:
    css: style_resume.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<body>
<!--
###SUMMARY

Biostatistics graduate student with prior research experience in data analysis of genetic data. Seeking for data intensive works with flexible fields of interest.
--->

### EDUCATION

#### **Columbia University, Mailman School of Public Health**
New York, NY, USA
<p style="text-align:left;">
Master of Science, Biostatistics/Statistical Genetics Track
<span style="float:right;">Expected 05/2020</span>
</br>**Relevant Courses**: Topics in Statistical Learning and Data Mining, Analysis of Longitudinal Data, Statistical Machine Learning, Statistical Inference, Introduction to Applied Statistics, Advanced Statistical Methods, Statistical Genetics Modeling 
</p>

#### **Indian Institute of Technology Guwahati (IIT Guwahati)** 	
Assam, India 
<p style="text-align:left;">
Bachelor of Technology, Biotechnology
<span style="float:right;">Graduation 06/2018</span>
</br>**Thesis**: Analysis of transcriptomics data of a natural Daphnia magna population under varying predation pressure.
</br>**Relevant Courses**: Biochemistry, Molecular Biology and Genetic Engineering, Immunology, Bioinformatics, Human Disease Biology
</p>

### SKILLS

#### **Tools**: 
 R (ggplot2, dplyr, tidyverse, shiny), SQL*, MS Excel ⃰, MS Word, MS PowerPoint 

#### **OS**:
 Windows, MacOS

#### **Languages**: 
 Bilingual in English/Hindi.


### EXPERIENCE

#### **Columbia University, School of Nursing** 			     
New York, New York
<span style="float:right;">03/2019 - Present</span>
<p style="text-align:left;">
Program Assistant

</p>

* Collaborate with a two person team in managing the school’s global initiative, sending out nearly 100 students to 17 different international sites.

* Transformed the whole application process and document processing by migrating from paper-based forms to electronic forms (DocuSign). 

* Carry out information tracking on MS Excel, report making on MS PowerPoint for the school’s leadership and survey design on Qualtrics. 

#### **Columbia University, Mailman School of Public Health** 			     
New York, New York
<span style="float:right;">03/2019 - Present</span>
<p style="text-align:left;">
Teaching Assistant, Department of Biostatistics

</p>

* Collaborated with a six-person team in managing weekly ofﬁce hours, assignments, quizzes and exams for the graduate-level Probability course, P8104 with 120 registered students. 

#### **Katholieke Universiteit (KU)** 			     
Leuven, Belgium
<span style="float:right;">05/2017 - 07/2017 and 12/2017 - 01/2018</span>
<p style="text-align:left;">
Visiting Scholar, Department of Biology

</br>Laboratory of Aquatic Ecology, Evolution and Conservation
</p>

* Analyzed high throughput transcriptomics (RNA-seq) data of a natural Daphnia magna population with around 30000 genes to understand the variation in gene expression level with varying predation pressure. 

* Performed Concordance Analysis, Principal Component Analysis (PCA) for sample quality control. 

* Produced visualizations using ggplot2 in R to understand the variation in gene expression over time using reaction norms.

<!--
#### **Indian Institute of Science, Bangalore (IISc)**
Karnataka, India
<p style="text-align:left;">
Summer Research Fellow, Department of Biochemistry
<span style="float:right;">05/2016 - 07/2016 </span>
</p>

* Investigated the possible mechanism behind limiting the spread of rDNA silencing at the RDN1 left boundary on yeast chromosome XII.

* Cloned a 600bp fragment to KanMX6 and then sub-cloned it into the plasmid pRO363 to check whether barrier activity is sequence specific or size dependent by analysing the mating efficiency of transformed yeast cells.

#### **Indian Institute of Technology, Guwahati** 		           
Assam, India 
<p style="text-align:left;">
Department of Biosciences and Bioengineering
<span style="float:right;">01/2017 - 03/2017</span>
</br>Laboratory of Aquatic Ecology, Evolution and Conservation
</p>

* Optimise expression and purification of a Cas4 mutant protein, Cas4E87A and analyse its activity.

* Purification of Cas4E87A mutant protein by the Hybrid Method followed by its quantification.

--->

### LEADERSHIP
<p style="text-align:left;">
**Student Mentor- Student’s Welfare Board, IIT-Guwahati**
<span style="float:right;">09/2016 - 04/2017</span>
</p>

* Mentored freshman students through various facets of the first academic year.

* Won the best student mentor award.

<p style="text-align:left;">
**Chief Organiser- TechExpo, Techniche, IIT-Guwahati**
<span style="float:right;  font-weight: normal;>10/2015 - 09/2016</span>
</p>

* Organised the largest student science expo of North-East of India.

* Handled a budget of nearly INR 15,00,000 (~21,000 USD).

* Organised the itinerary of judges from all across the world such as Dr. Thomas Barclay (NASA).

<p style="text-align:left;">
**Head- Industrial Conclave, Exhibitions and Literary Module, Techniche, IIT-Guwahati** 
<span style="float:right;">10/2015 - 09/2016</span>
</p>

* Lead a team of highly motivated students in organizing three high profile events.

* Managed the timeline, itinerary, budgeting and communication with all other parties.

* The exhibitions at IIT-Guwahati saw a footfall of nearly 30,000 people.

<p style="text-align:left;">
**Member- National Service Scheme** 	
<span style="float:right;">07/2015 - 04/2016</span>
</p>
						 	                                                  
<p style="text-align:left;">
**Member- Montage, The Photography Club of IIT-Guwahati**	
<span style="float:right;">07/2014 - 05/2018</span>
</p>
</body>


*: Basic proficiency
